use_frameworks!

target 'NokeMobileLibrary_Example' do
  use_frameworks! :linkage => :static
  pod 'NokeMobileLibrary', :path => '../'

  target 'NokeMobileLibrary_Tests' do
    inherit! :search_paths

  end
end
