use_frameworks!

target 'NokeMobileLibrary_Example' do
  pod 'NokeMobileLibrary', :path => '../'

  target 'NokeMobileLibrary_Tests' do
    inherit! :search_paths

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
